version: "3"
services:
  mongodb:
    container_name: mongodb_Container
    image: mongo
    restart: always
    volumes:
      - mongodb:/data/db
    ports:
      - 27018:27017

  nodejs:
    build: .
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      MONGO_URI: mongodb://mongodb:27017/sertis_back-end_internship
      JWT_SECRET: mySecureKey
    depends_on:
      - mongodb

volumes:
  mongodb: {}